# All
# >> Google
DOMAIN-SUFFIX,g.co
DOMAIN-SUFFIX,youtu.be
DOMAIN-SUFFIX,googleapis.cn
DOMAIN-SUFFIX,gmail.com
DOMAIN-SUFFIX,ggpht.com
DOMAIN-SUFFIX,ytimg.com
DOMAIN-SUFFIX,youtube.com
DOMAIN-KEYWORD,google
DOMAIN-WILDCARD,gvt*.com

# >> CDN
# >> Amazon Trust OCSP
DOMAIN-WILDCARD,ocsp.*.amazontrust.com
# 18Comic / JMComic
DOMAIN,cdn-msp.18comic.vip
DOMAIN-WILDCARD,cdn-msp?.18comic.vip
DOMAIN,cdn-msp.jmcomic.me
DOMAIN-WILDCARD,cdn-msp?.jmcomic.me
# Video
DOMAIN-WILDCARD,*.ffzy-online?.com
DOMAIN-WILDCARD,*.ffzy-play?.com
DOMAIN-WILDCARD,*.kuaikan-cdn?.com
DOMAIN-WILDCARD,*.lz-cdn?.com
DOMAIN-WILDCARD,*.lz-cdn??.com
DOMAIN-WILDCARD,*.fsvod?.com

# >> Other
DOMAIN-SUFFIX,x.com
DOMAIN-SUFFIX,cdninstagram.com
DOMAIN-SUFFIX,twimg.com
DOMAIN-SUFFIX,pixiv.net
DOMAIN-SUFFIX,18comic.vip
DOMAIN-SUFFIX,18comic.org
DOMAIN-SUFFIX,githubusercontent.com
DOMAIN-SUFFIX,redd.it
DOMAIN-SUFFIX,themoviedb.org
DOMAIN-SUFFIX,thetvdb.com
DOMAIN-SUFFIX,tmdb.org


DOMAIN-KEYWORD,Reddit
DOMAIN-KEYWORD,github
DOMAIN-KEYWORD,twitter
DOMAIN-KEYWORD,discord
DOMAIN-KEYWORD,facebook
DOMAIN-KEYWORD,instagram
