# === 社交与平台 ===
# -- Twitter / X --
DOMAIN-SUFFIX,periscope.tv
DOMAIN-SUFFIX,pscp.tv
DOMAIN-SUFFIX,t.co
DOMAIN-SUFFIX,twimg.co
DOMAIN-SUFFIX,twimg.com
DOMAIN-SUFFIX,twimg.org
DOMAIN-SUFFIX,twitpic.com
DOMAIN-SUFFIX,twitter.com
DOMAIN-SUFFIX,twitter.jp
DOMAIN-SUFFIX,vine.co
DOMAIN-SUFFIX,x.com

# -- 其他社交与平台 --
DOMAIN-SUFFIX,18comic.org
DOMAIN-SUFFIX,18comic.vip
DOMAIN-SUFFIX,cdninstagram.com
DOMAIN-SUFFIX,fb.me
DOMAIN-SUFFIX,fbcdn.net
DOMAIN-SUFFIX,hanime1.me
DOMAIN-SUFFIX,pixiv.net
DOMAIN-SUFFIX,redd.it
DOMAIN-SUFFIX,telegram.org
DOMAIN-SUFFIX,themoviedb.org
DOMAIN-SUFFIX,thetvdb.com
DOMAIN-SUFFIX,tmdb.org

# === 开发与资料 ===
DOMAIN-SUFFIX,githubusercontent.com

# === 关键字匹配 ===
DOMAIN-KEYWORD,discord
DOMAIN-KEYWORD,facebook
DOMAIN-KEYWORD,github
DOMAIN-KEYWORD,instagram
DOMAIN-KEYWORD,Reddit
DOMAIN-KEYWORD,twitter
DOMAIN-KEYWORD,whatsapp
