# === Google ===
DOMAIN-SUFFIX,g.co
DOMAIN-SUFFIX,gmail.com
DOMAIN-SUFFIX,googleapis.cn
DOMAIN-SUFFIX,youtube.com
DOMAIN-SUFFIX,youtu.be
DOMAIN-SUFFIX,ytimg.com
DOMAIN-SUFFIX,gstatic.com

# === 社交与平台 ===
DOMAIN-SUFFIX,fb.me
DOMAIN-SUFFIX,fbcdn.net
DOMAIN-SUFFIX,twimg.com
DOMAIN-SUFFIX,x.com
DOMAIN-SUFFIX,cdninstagram.com
DOMAIN-SUFFIX,redd.it
DOMAIN-SUFFIX,telegram.org
DOMAIN-SUFFIX,pixiv.net
DOMAIN-SUFFIX,hanime1.me
DOMAIN-SUFFIX,18comic.vip
DOMAIN-SUFFIX,18comic.org

# === 开发与资料 ===
DOMAIN-SUFFIX,githubusercontent.com
DOMAIN-SUFFIX,themoviedb.org
DOMAIN-SUFFIX,thetvdb.com
DOMAIN-SUFFIX,tmdb.org

# === 其他后缀 ===
DOMAIN-SUFFIX,tw
DOMAIN-SUFFIX,oculus.com
DOMAIN-SUFFIX,oculuscdn.com

# === 关键字匹配 ===
DOMAIN-KEYWORD,google
DOMAIN-KEYWORD,gmail
DOMAIN-KEYWORD,youtube
DOMAIN-KEYWORD,facebook
DOMAIN-KEYWORD,twitter
DOMAIN-KEYWORD,instagram
DOMAIN-KEYWORD,dropbox
DOMAIN-KEYWORD,blogspot
DOMAIN-KEYWORD,whatsapp
DOMAIN-KEYWORD,Reddit
DOMAIN-KEYWORD,github
DOMAIN-KEYWORD,discord

# === 通配符匹配 ===
DOMAIN-WILDCARD,gvt*.com
