DOMAIN-SUFFIX,qq.com
DOMAIN-SUFFIX,jd.com
DOMAIN-SUFFIX,hupu.com
DOMAIN-SUFFIX,baidu.com
DOMAIN-SUFFIX,tmall.com
DOMAIN-SUFFIX,youku.com
DOMAIN-SUFFIX,alipan.com
DOMAIN-SUFFIX,bilivideo.com
DOMAIN-SUFFIX,douban.com
DOMAIN-SUFFIX,douyin.com
DOMAIN-SUFFIX,meituan.com
DOMAIN-SUFFIX,meituan.net
DOMAIN-SUFFIX,netease.com
DOMAIN-SUFFIX,weibo.com
DOMAIN-SUFFIX,weibocdn.com
DOMAIN-SUFFIX,music.126.net
DOMAIN-SUFFIX,music.163.com
DOMAIN,infuseku.xyz
DOMAIN,app.localhost.qaq.wiki

#tencent
DOMAIN-SUFFIX,tencentmusic.com
DOMAIN-SUFFIX,tcdnlive.com
DOMAIN-SUFFIX,qlivecdn.com
DOMAIN-SUFFIX,myqcloud.com
DOMAIN-SUFFIX,udqqimg.com
DOMAIN-SUFFIX,tencent.com
DOMAIN-SUFFIX,weiyun.com
DOMAIN-SUFFIX,weixin.com
DOMAIN-SUFFIX,qqmail.com
DOMAIN-SUFFIX,qcloud.com
DOMAIN-SUFFIX,gdtimg.com
DOMAIN-SUFFIX,gtimg.com
DOMAIN-SUFFIX,tencentcs.cn
DOMAIN-SUFFIX,qlogo.cn
DOMAIN-SUFFIX,gtimg.cn
DOMAIN-SUFFIX,qpic.cn
DOMAIN-SUFFIX,tencent.com.cn
DOMAIN-SUFFIX,gtimg.com.cn

# All
DOMAIN-KEYWORD,alipay
DOMAIN-KEYWORD,taobao
DOMAIN-KEYWORD,alicdn
DOMAIN-KEYWORD,aliyun
DOMAIN-KEYWORD,iqiyi
DOMAIN-KEYWORD,xiaomi
DOMAIN-KEYWORD,tencent
DOMAIN-KEYWORD,bilibili

# video site
DOMAIN-SUFFIX,doubanio.com
DOMAIN-SUFFIX,movie.douban.com
DOMAIN-SUFFIX,mddcloud.com.cn
DOMAIN-SUFFIX,aliyundrive.asia
DOMAIN-SUFFIX,ddys.info
DOMAIN-SUFFIX,ddys.wiki
DOMAIN-SUFFIX,ddys.pro
DOMAIN-SUFFIX,ddys.mov
DOMAIN-SUFFIX,ddys.art
DOMAIN-SUFFIX,zh188.net
DOMAIN-SUFFIX,kczybf.com
DOMAIN-SUFFIX,mixpanel.com
DOMAIN-SUFFIX,appsflyer.com
DOMAIN-SUFFIX,tv.apple.com
DOMAIN-SUFFIX,ctyunxs.cn
DOMAIN-SUFFIX,hls.aoxtv.com
DOMAIN-SUFFIX,kuaikan-api.com
DOMAIN-SUFFIX,cz.cz01.site
DOMAIN-SUFFIX,czzy88.com
DOMAIN-SUFFIX,czzy22.com
DOMAIN-SUFFIX,czzy66.com
DOMAIN-SUFFIX,cz233.com
DOMAIN-SUFFIX,CZZ9.COM
DOMAIN-SUFFIX,czzy.top
DOMAIN-SUFFIX,czys.top
DOMAIN-SUFFIX,czzy77.com
DOMAIN-SUFFIX,wogg.link
DOMAIN-SUFFIX,xxooo.cf
DOMAIN-SUFFIX,wogg.xyz
DOMAIN-SUFFIX,pstatp.com
DOMAIN-SUFFIX,ikzybf.com
DOMAIN-SUFFIX,yanetflix.one
DOMAIN-SUFFIX,bfikuncdn.com
DOMAIN-SUFFIX,ikunzyapi.com
DOMAIN-SUFFIX,kkzycdn.com
DOMAIN-SUFFIX,libvio.mov
DOMAIN-SUFFIX,libvio.cc
DOMAIN-SUFFIX,libvio.la
DOMAIN-SUFFIX,libvio.pro
DOMAIN-SUFFIX,libvio.fun
DOMAIN-SUFFIX,libvio.me
DOMAIN-SUFFIX,libvio.in
DOMAIN-SUFFIX,libvio.site
DOMAIN-SUFFIX,libvio.art
DOMAIN-SUFFIX,libvio.com
DOMAIN-SUFFIX,libvio.vip
DOMAIN-SUFFIX,libvio.pw
DOMAIN-SUFFIX,libvio.link
DOMAIN-SUFFIX,czzymovie.com
IP-CIDR,216.180.0.0/16
IP-CIDR,103.160.204.120/32
IP-CIDR,138.199.9.104/32
DOMAIN-KEYWORD,ffzy-play
DOMAIN-KEYWORD,bfzycdn.com
DOMAIN-KEYWORD,lzcdn
DOMAIN-KEYWORD,cdnlz
DOMAIN-KEYWORD,lz-cdn
DOMAIN-KEYWORD,default.akamaized.net
DOMAIN-KEYWORD,vip.ffzy-online
DOMAIN-KEYWORD,vip.ffzy-play
DOMAIN-KEYWORD,ffzyread
DOMAIN-KEYWORD,tt.cuc.myqcloud.com.cn

# Apps
USER-AGENT,WeChat*
USER-AGENT,MicroMessenger Client
USER-AGENT,NeteaseMusic*
# China
DOMAIN-SUFFIX,cn
