DOMAIN-SUFFIX,byteoversea.com
DOMAIN-SUFFIX,ibytedtos.com
DOMAIN-SUFFIX,ipstatp.com
DOMAIN-SUFFIX,isnssdk.com
DOMAIN-SUFFIX,muscdn.com
DOMAIN-SUFFIX,musical.ly
DOMAIN-SUFFIX,tiktok.com
DOMAIN-SUFFIX,tiktok.us
DOMAIN-SUFFIX,tiktokv.us
DOMAIN-SUFFIX,tik-tokapi.com
DOMAIN-SUFFIX,tiktokv.com
DOMAIN-SUFFIX,tiktokw.com
DOMAIN-KEYWORD,-tiktokcdn-com
USER-AGENT,TikTok*